//
//  ConvertorInteractor.swift
//  Convertor
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift

class ConvertorInteractor: ConvertorInteractorProtocol {

    
    weak var presenter: ConvertorPresenterProtocol?
    
    func getPrivateCurrency(date: Double?) -> Observable<PrivateResponse> {
        return PrivateCurrencyRequest.getCurrency(date: date)
    }
    
    func getNBUCurrency(date: Double?) -> Observable<[NBUResponse]> {
        return NBUCurrencyRequest.getCurrency(date: date)
    }
}
