//
//  ConvertorProtocols.swift
//  Convertor
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol ConvertorWireframeProtocol: class {

}
//MARK: Presenter -
protocol ConvertorPresenterProtocol: class {
    func getPrivateCurrency(date: Double?)
    func getNBUCurrency(date: Double?)
}

//MARK: Interactor -
protocol ConvertorInteractorProtocol: class {

  var presenter: ConvertorPresenterProtocol?  { get set }
    func getPrivateCurrency(date: Double?) -> Observable<PrivateResponse>
    func getNBUCurrency(date: Double?) -> Observable<[NBUResponse]>
}

//MARK: View -
protocol ConvertorViewProtocol: class {

  var presenter: ConvertorPresenterProtocol?  { get set }
    func setPrivateCurrency(response: PrivateResponse)
    func setNBUCurrency(response: [NBUResponse])
}
