//
//  ConvertorRouter.swift
//  Convertor
//
//  Created George Kyrylenko on 9/3/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConvertorRouter: ConvertorWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: ConvertorViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = ConvertorInteractor()
        let router = ConvertorRouter()
        let presenter = ConvertorPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
}
